/* ---------------------------------------------------------------
   Cheatsheet data — curated from README.md
   Each entry: { lang, cat, shortcut, desc, example, difficulty }
   difficulty: 'easy' | 'medium' | 'hard'
   --------------------------------------------------------------- */

const SHORTCUTS = [
  // ---------------- HTML ----------------
  { lang: "html", cat: "Emmet", shortcut: "html:5", difficulty: "easy", desc: "Full HTML5 boilerplate.", example: "<!DOCTYPE html>\n<html lang=\"en\">\n<head>...</head>\n<body>...</body>\n</html>" },
  { lang: "html", cat: "Emmet", shortcut: "div.card", difficulty: "easy", desc: "Div with a class.", example: '<div class="card"></div>' },
  { lang: "html", cat: "Emmet", shortcut: "div#app", difficulty: "easy", desc: "Div with an id.", example: '<div id="app"></div>' },
  { lang: "html", cat: "Emmet", shortcut: "ul>li*5", difficulty: "easy", desc: "5 nested list items.", example: "<ul>\n  <li></li>\n  <li></li>\n  <li></li>\n  <li></li>\n  <li></li>\n</ul>" },
  { lang: "html", cat: "Emmet", shortcut: "nav>ul>li*3>a", difficulty: "easy", desc: "Nav with 3 links.", example: "<nav>\n  <ul>\n    <li><a href=\"\"></a></li>\n    <li><a href=\"\"></a></li>\n    <li><a href=\"\"></a></li>\n  </ul>\n</nav>" },
  { lang: "html", cat: "Emmet", shortcut: "form>input+input+button", difficulty: "easy", desc: "Form fields chained with +.", example: "<form>\n  <input type=\"text\">\n  <input type=\"text\">\n  <button></button>\n</form>" },
  { lang: "html", cat: "Emmet", shortcut: "table>tr*3>td*4", difficulty: "medium", desc: "Table with 3 rows, 4 columns.", example: "<table>\n  <tr><td></td><td></td><td></td><td></td></tr>\n  ...\n</table>" },
  { lang: "html", cat: "Emmet", shortcut: "input:email", difficulty: "easy", desc: "Email input with name/id.", example: '<input type="email" name="" id="">' },
  { lang: "html", cat: "Emmet", shortcut: "a:link", difficulty: "easy", desc: "Anchor with href scaffold.", example: '<a href="http://"></a>' },
  { lang: "html", cat: "Emmet", shortcut: "p{Hello World}", difficulty: "easy", desc: "Element with inner text.", example: "<p>Hello World</p>" },
  { lang: "html", cat: "Emmet", shortcut: "p>lorem10", difficulty: "easy", desc: "10 words of Lorem Ipsum.", example: "<p>Lorem ipsum dolor sit amet...</p>" },
  { lang: "html", cat: "Emmet", shortcut: "li{Item $}*5", difficulty: "easy", desc: "Numbered list items.", example: "<li>Item 1</li>\n<li>Item 2</li>\n...\n<li>Item 5</li>" },
  { lang: "html", cat: "Elements", shortcut: "<header>", difficulty: "easy", desc: "Top section: logo, nav.", example: "<header>...</header>" },
  { lang: "html", cat: "Elements", shortcut: "<main>", difficulty: "easy", desc: "Primary content of the page.", example: "<main>...</main>" },
  { lang: "html", cat: "Elements", shortcut: "<section>", difficulty: "easy", desc: "Standalone thematic grouping.", example: "<section id=\"pricing\">...</section>" },
  { lang: "html", cat: "Elements", shortcut: "<article>", difficulty: "easy", desc: "Independent, self-contained content.", example: "<article>Blog post</article>" },
  { lang: "html", cat: "Elements", shortcut: "<aside>", difficulty: "easy", desc: "Sidebar / tangential content.", example: "<aside>Related links</aside>" },
  { lang: "html", cat: "Elements", shortcut: "<figure>+<figcaption>", difficulty: "medium", desc: "Media with a caption.", example: "<figure>\n  <img src=\"cat.jpg\" alt=\"Cat\">\n  <figcaption>A cat</figcaption>\n</figure>" },
  { lang: "html", cat: "Elements", shortcut: "<details>+<summary>", difficulty: "medium", desc: "Toggleable disclosure widget.", example: "<details>\n  <summary>More</summary>\n  Hidden content\n</details>" },
  { lang: "html", cat: "Elements", shortcut: "<dialog>", difficulty: "medium", desc: "Native modal dialog box.", example: '<dialog open>Hello</dialog>' },
  { lang: "html", cat: "Elements", shortcut: "<picture>", difficulty: "medium", desc: "Responsive image sources.", example: "<picture>\n  <source srcset=\"img.webp\" type=\"image/webp\">\n  <img src=\"img.jpg\" alt=\"\">\n</picture>" },
  { lang: "html", cat: "Elements", shortcut: "<template>", difficulty: "medium", desc: "Inert markup for JS cloning.", example: '<template id="row">...</template>' },
  { lang: "html", cat: "Elements", shortcut: "<progress>", difficulty: "easy", desc: "Task completion bar.", example: '<progress value="70" max="100"></progress>' },
  { lang: "html", cat: "Elements", shortcut: "<meter>", difficulty: "medium", desc: "Scalar value within a range.", example: '<meter value="6" max="10"></meter>' },
  { lang: "html", cat: "Elements", shortcut: "<datalist>", difficulty: "medium", desc: "Autocomplete options for an input.", example: '<input list="cities">\n<datalist id="cities"><option>NYC</option></datalist>' },
  { lang: "html", cat: "Attributes", shortcut: "loading=\"lazy\"", difficulty: "easy", desc: "Defers off-screen image loading.", example: '<img src="big.jpg" loading="lazy" alt="">' },
  { lang: "html", cat: "Attributes", shortcut: "contenteditable", difficulty: "easy", desc: "Makes any element user-editable.", example: '<div contenteditable="true"></div>' },
  { lang: "html", cat: "Attributes", shortcut: "data-*", difficulty: "easy", desc: "Custom data attributes for JS hooks.", example: '<div data-user-id="42"></div>' },
  { lang: "html", cat: "Entities", shortcut: "&nbsp;", difficulty: "easy", desc: "Non-breaking space.", example: "Prevents line break between words" },
  { lang: "html", cat: "Entities", shortcut: "&copy;", difficulty: "easy", desc: "Copyright symbol.", example: "© 2025" },
  { lang: "html", cat: "Entities", shortcut: "&rarr;", difficulty: "easy", desc: "Right arrow.", example: "→" },
  { lang: "html", cat: "Notepad++", shortcut: "Ctrl+Shift+C", difficulty: "easy", desc: "Comment out selection.", example: "<!-- selected text -->" },
  { lang: "html", cat: "Notepad++", shortcut: "Ctrl+D", difficulty: "easy", desc: "Duplicate current line.", example: "Copies line directly below" },
  { lang: "html", cat: "VS Code", shortcut: "! + Tab", difficulty: "easy", desc: "Emmet HTML5 boilerplate.", example: "Expands to full document structure" },
  { lang: "html", cat: "VS Code", shortcut: "Ctrl+Shift+'", difficulty: "easy", desc: "Wrap selection with abbreviation.", example: "Wraps selected text in a tag" },
  { lang: "html", cat: "VS Code", shortcut: "Alt+Shift+F", difficulty: "easy", desc: "Format the whole document.", example: "Pretty-prints your HTML" },

  // ---------------- CSS ----------------
  { lang: "css", cat: "Emmet", shortcut: "df", difficulty: "easy", desc: "display: flex;", example: "display: flex;" },
  { lang: "css", cat: "Emmet", shortcut: "dg", difficulty: "easy", desc: "display: grid;", example: "display: grid;" },
  { lang: "css", cat: "Emmet", shortcut: "posa", difficulty: "easy", desc: "position: absolute;", example: "position: absolute;" },
  { lang: "css", cat: "Emmet", shortcut: "m10a", difficulty: "easy", desc: "Auto margin shorthand.", example: "margin: 10px auto;" },
  { lang: "css", cat: "Emmet", shortcut: "jc:c", difficulty: "easy", desc: "justify-content: center;", example: "justify-content: center;" },
  { lang: "css", cat: "Emmet", shortcut: "ai:c", difficulty: "easy", desc: "align-items: center;", example: "align-items: center;" },
  { lang: "css", cat: "Emmet", shortcut: "bxsh:r", difficulty: "easy", desc: "Red box shadow shorthand.", example: "box-shadow: 0 0 0 red;" },
  { lang: "css", cat: "Emmet", shortcut: "br:50p", difficulty: "easy", desc: "border-radius: 50%; (circle)", example: "border-radius: 50%;" },
  { lang: "css", cat: "Emmet", shortcut: "ov:h", difficulty: "easy", desc: "overflow: hidden;", example: "overflow: hidden;" },
  { lang: "css", cat: "Emmet", shortcut: "cur:p", difficulty: "easy", desc: "cursor: pointer;", example: "cursor: pointer;" },
  { lang: "css", cat: "Emmet", shortcut: "tt:u", difficulty: "easy", desc: "text-transform: uppercase;", example: "text-transform: uppercase;" },
  { lang: "css", cat: "Layout", shortcut: "display: grid", difficulty: "medium", desc: "2D layout system.", example: "display: grid;\ngrid-template-columns: repeat(3, 1fr);\ngap: 20px;" },
  { lang: "css", cat: "Layout", shortcut: "place-items: center", difficulty: "medium", desc: "Centers content in a grid.", example: "display: grid;\nplace-items: center;" },
  { lang: "css", cat: "Layout", shortcut: "position: sticky", difficulty: "medium", desc: "Sticks while scrolling within parent.", example: "position: sticky;\ntop: 0;" },
  { lang: "css", cat: "Layout", shortcut: "aspect-ratio", difficulty: "medium", desc: "Forces a width:height ratio.", example: "aspect-ratio: 16 / 9;" },
  { lang: "css", cat: "Flexbox", shortcut: "flex: 1", difficulty: "medium", desc: "Grow to fill available space.", example: "flex: 1;" },
  { lang: "css", cat: "Flexbox", shortcut: "gap: 1rem", difficulty: "medium", desc: "Space between flex/grid children.", example: "display: flex;\ngap: 1rem;" },
  { lang: "css", cat: "Effects", shortcut: "backdrop-filter", difficulty: "medium", desc: "Glassmorphism blur effect.", example: "backdrop-filter: blur(10px);" },
  { lang: "css", cat: "Effects", shortcut: "clip-path", difficulty: "medium", desc: "Clips into a custom shape.", example: "clip-path: circle(50%);" },
  { lang: "css", cat: "Effects", shortcut: "box-shadow", difficulty: "medium", desc: "Adds a drop shadow.", example: "box-shadow: 0 4px 8px rgba(0,0,0,.1);" },
  { lang: "css", cat: "Animation", shortcut: "transition", difficulty: "medium", desc: "Smooth property changes.", example: "transition: transform 0.3s ease;" },
  { lang: "css", cat: "Animation", shortcut: "@keyframes", difficulty: "medium", desc: "Defines multi-step animations.", example: "@keyframes slideIn {\n  from { opacity: 0; }\n  to { opacity: 1; }\n}" },
  { lang: "css", cat: "Animation", shortcut: "transform", difficulty: "medium", desc: "Scale, rotate, translate elements.", example: "transform: scale(1.05) translateY(-4px);" },
  { lang: "css", cat: "Variables", shortcut: "--custom-prop", difficulty: "medium", desc: "Reusable CSS custom properties.", example: ":root { --brand: #6c5ce7; }\n.btn { color: var(--brand); }" },
  { lang: "css", cat: "Responsive", shortcut: "@media", difficulty: "medium", desc: "Conditional styles by viewport.", example: "@media (max-width: 768px) {\n  .sidebar { display: none; }\n}" },
  { lang: "css", cat: "Typography", shortcut: "text-overflow: ellipsis", difficulty: "medium", desc: "Truncates overflowing text.", example: "overflow: hidden;\nwhite-space: nowrap;\ntext-overflow: ellipsis;" },
  { lang: "css", cat: "Typography", shortcut: "line-clamp", difficulty: "hard", desc: "Truncates to N lines.", example: "display: -webkit-box;\n-webkit-line-clamp: 3;\n-webkit-box-orient: vertical;\noverflow: hidden;" },
  { lang: "css", cat: "Selectors", shortcut: "&:hover (SCSS)", difficulty: "medium", desc: "Nested pseudo-class in Sass.", example: ".btn {\n  &:hover { background: darkblue; }\n}" },
  { lang: "css", cat: "Selectors", shortcut: ":nth-child(odd)", difficulty: "medium", desc: "Targets alternating elements.", example: "li:nth-child(odd) { background: #f5f5f5; }" },
  { lang: "css", cat: "Scrollbar", shortcut: "::-webkit-scrollbar", difficulty: "hard", desc: "Custom scrollbar styling.", example: "::-webkit-scrollbar { width: 10px; }\n::-webkit-scrollbar-thumb { background: #888; }" },

  // ---------------- JS ----------------
  { lang: "js", cat: "ES6+", shortcut: "let / const", difficulty: "easy", desc: "Block-scoped variables.", example: "const name = 'Eli';\nlet age = 22;" },
  { lang: "js", cat: "ES6+", shortcut: "arrow fn", difficulty: "easy", desc: "Concise function syntax.", example: "const add = (a, b) => a + b;" },
  { lang: "js", cat: "ES6+", shortcut: "template literal", difficulty: "easy", desc: "String interpolation.", example: "const msg = `Hello ${name}!`;" },
  { lang: "js", cat: "ES6+", shortcut: "destructuring", difficulty: "medium", desc: "Unpack values from objects/arrays.", example: "const { name, age = 0 } = user;\nconst [first, ...rest] = arr;" },
  { lang: "js", cat: "ES6+", shortcut: "spread / rest", difficulty: "medium", desc: "Expand or collect values.", example: "const merged = { ...a, ...b };\nfunction sum(...nums) {}" },
  { lang: "js", cat: "ES6+", shortcut: "optional chaining", difficulty: "medium", desc: "Safe nested property access.", example: "const city = user?.address?.city ?? 'Unknown';" },
  { lang: "js", cat: "Arrays", shortcut: "arr.map()", difficulty: "medium", desc: "Transform each item into a new array.", example: "const doubled = [1,2,3].map(n => n * 2);\n// [2, 4, 6]" },
  { lang: "js", cat: "Arrays", shortcut: "arr.filter()", difficulty: "medium", desc: "Keep only matching items.", example: "const evens = [1,2,3,4].filter(n => n % 2 === 0);\n// [2, 4]" },
  { lang: "js", cat: "Arrays", shortcut: "arr.reduce()", difficulty: "hard", desc: "Accumulate to a single value.", example: "const sum = [1,2,3].reduce((a,b) => a + b, 0);\n// 6" },
  { lang: "js", cat: "Arrays", shortcut: "arr.find()", difficulty: "medium", desc: "Get the first matching item.", example: "const user = users.find(u => u.id === 2);" },
  { lang: "js", cat: "Arrays", shortcut: "arr.some() / every()", difficulty: "medium", desc: "Test if some/all items match.", example: "const hasEven = nums.some(n => n % 2 === 0);" },
  { lang: "js", cat: "Arrays", shortcut: "[...new Set(arr)]", difficulty: "medium", desc: "De-duplicate an array.", example: "const unique = [...new Set([1,1,2,3])];\n// [1, 2, 3]" },
  { lang: "js", cat: "Strings", shortcut: "str.includes()", difficulty: "easy", desc: "Check for a substring.", example: "'Hello'.includes('ell'); // true" },
  { lang: "js", cat: "Strings", shortcut: "str.padStart()", difficulty: "easy", desc: "Pad a string to a length.", example: "'5'.padStart(3, '0'); // '005'" },
  { lang: "js", cat: "Strings", shortcut: "str.replaceAll()", difficulty: "easy", desc: "Replace every occurrence.", example: "'a-b-c'.replaceAll('-', '_'); // 'a_b_c'" },
  { lang: "js", cat: "DOM", shortcut: "querySelector()", difficulty: "medium", desc: "Select the first matching element.", example: "const btn = document.querySelector('.btn');" },
  { lang: "js", cat: "DOM", shortcut: "addEventListener()", difficulty: "medium", desc: "Listen for an event.", example: "btn.addEventListener('click', () => {\n  console.log('clicked!');\n});" },
  { lang: "js", cat: "DOM", shortcut: "classList.toggle()", difficulty: "medium", desc: "Toggle a CSS class.", example: "el.classList.toggle('active');" },
  { lang: "js", cat: "DOM", shortcut: "dataset", difficulty: "easy", desc: "Read data-* attributes.", example: "<div data-id=\"42\">\nel.dataset.id; // '42'" },
  { lang: "js", cat: "Async", shortcut: "async / await", difficulty: "hard", desc: "Write promises like sync code.", example: "async function getData() {\n  const res = await fetch(url);\n  return res.json();\n}" },
  { lang: "js", cat: "Async", shortcut: "Promise.all()", difficulty: "hard", desc: "Wait for multiple promises.", example: "const [a, b] = await Promise.all([p1, p2]);" },
  { lang: "js", cat: "Patterns", shortcut: "debounce()", difficulty: "hard", desc: "Delay a function until input settles.", example: "function debounce(fn, delay=300){\n  let t;\n  return (...a) => {\n    clearTimeout(t);\n    t = setTimeout(() => fn(...a), delay);\n  };\n}" },
  { lang: "js", cat: "Patterns", shortcut: "throttle()", difficulty: "hard", desc: "Limit call frequency.", example: "function throttle(fn, limit=300){\n  let wait;\n  return (...a) => {\n    if (!wait) { fn(...a); wait = true;\n      setTimeout(() => wait = false, limit); }\n  };\n}" },
  { lang: "js", cat: "Patterns", shortcut: "structuredClone()", difficulty: "medium", desc: "Deep clone any value.", example: "const copy = structuredClone(original);" },
  { lang: "js", cat: "Patterns", shortcut: "?? nullish coalescing", difficulty: "medium", desc: "Default only for null/undefined.", example: "const count = input ?? 0;" },
  { lang: "js", cat: "Objects", shortcut: "Object.entries()", difficulty: "easy", desc: "Get [key, value] pairs.", example: "Object.entries({a:1,b:2});\n// [['a',1], ['b',2]]" },
  { lang: "js", cat: "JSON", shortcut: "JSON.stringify() / parse()", difficulty: "easy", desc: "Convert to/from JSON text.", example: "JSON.stringify({a:1}); // '{\"a\":1}'\nJSON.parse('{\"a\":1}');" },
];
